# Generated by Django 5.2.1 on 2026-02-16 15:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='filters',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, default='light', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet_prefs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='prefer_not', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, default='maintain', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.JSONField(blank=True, default=api.models.default_health_conditions),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_change_kg_6mo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
